services:
  initiator:
    build: versions/
    volumes:
      - ./versions:/tmp
    hostname: edhoc-initiator
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    networks:
      common_net:
        ipv4_address: 192.168.56.101

  responder:
    build: versions/
    volumes:
      - ./versions:/tmp
    hostname: edhoc-responder
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    networks:
      common_net:
        ipv4_address: 192.168.56.102

networks:
  common_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.56.0/24
    driver_opts:
      com.docker.network.bridge.name: edhoc_net

